steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: "Build the container"
    args: ["build", "-t", "eu.gcr.io/casehubdk/bazelisk-docker:$SHORT_SHA", "."]

  - name: 'gcr.io/cloud-builders/docker'
    id: "Build the container with latex"
    args: ["build", "-t", "eu.gcr.io/casehubdk/bazelisk-docker:latex-$SHORT_SHA", "-f", "Dockerfile.withlatex", "."]

  - name: 'gcr.io/cloud-builders/docker'
    id: "Push the container"
    args: ["push", "eu.gcr.io/casehubdk/bazelisk-docker:$SHORT_SHA"]

  - name: 'gcr.io/cloud-builders/docker'
    id: "Push the container with latex"
    args: ["push", "eu.gcr.io/casehubdk/bazelisk-docker:latex-$SHORT_SHA"]
options:
  machineType: "N1_HIGHCPU_8"
timeout: "900s"
